import WidgetProvider from "@/context";
import Providers from "@/redux/Provider";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kuesioner",
  description: "Generated by Muhammad Jaury",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        <Providers>
          <WidgetProvider>{children}</WidgetProvider>
        </Providers>
      </body>
    </html>
  );
}
